# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9d429afa5f38b8214013da6f01b0fe7917dce4c6dad6c0384f087473dd531ba5ca00aa5064bca893cf6690304b73ef6abbca873c046252617243b02a6e7547c

test:
  secret_key_base: 8fa67101bacdfaae881c0c66f2a0be81d33c8340060e96fae72eb0a3a9e37fe1a8c7d2e1e228ac84e18ceaf153c92027e0f38982ee7141407f940f87a158df9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= File.read("/run/secrets/secretkeybase") {'changeme'} %>
